# Generated by Django 5.2.2 on 2025-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('ipv6', models.GenericIPAddressField(protocol='IPv6')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
