name: CI/CD Pipeline for IP Converter

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
        working-directory: ./client
      - name: Run tests
        run: yarn test
        working-directory: ./client

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
        working-directory: ./server
      - name: Run migrations
        run: poetry run python manage.py migrate
        working-directory: ./server
      - name: Run tests
        run: poetry run python manage.py test
        working-directory: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker build -t username/ip-converter-frontend ./client
          docker build -t username/ip-converter-backend ./server
          docker push username/ip-converter-frontend
          docker push username/ip-converter-backend
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull username/ip-converter-frontend
            docker pull username/ip-converter-backend
            docker-compose up -d